name: flagsmith
description: >-
  Flutter Client SDK for https://www.flagsmith.com/, Flagsmith is 100% Open
  Source. Host yourself or let us take care of the hosting.

version: 2.2.0-beta.2
homepage: https://github.com/Flagsmith/flagsmith-flutter-client
repository: https://github.com/Flagsmith/flagsmith-flutter-client
issue_tracker: https://github.com/Flagsmith/flagsmith-flutter-client/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flagsmith_core: ^2.1.0+2
  collection: ^1.15.0
  dio: ^4.0.0  
  rxdart: ">=0.26.0 <=0.27.2"
dev_dependencies:
  test:  ">=1.16.0 <=1.17.12"
  lints: ^1.0.1
  http_mock_adapter: ^0.3.2
  mockito: ^5.0.15
  test_coverage_badge: ^0.2.0